owner: tsukuba-hpcs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DNS Primary
    url: ns.omni.hpcc.jp
    check: "tcp-ping"
    port: 53
  - name: DNS Secondary
    url: fs.omni.hpcc.jp
    check: "tcp-ping"
    port: 53
  - name: Gateway (SSH)
    url: gw.omni.hpcc.jp
    check: "tcp-ping"
    port: 22

assignees:
  - onokatio
  - namachan10777
  - otatebe
  - k5342
  - range3
  - KoyamaSohei

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Omni Cluster Status Page
  introTitle: Omni Cluster Status Page
  introMessage: Omni Clusterの基幹系の死活監視をします
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: HPCSLab
      href: https://www.hpcs.cs.tsukuba.ac.jp/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
